//go:build !ignore_autogenerated

/*
Copyright 2026 jr42.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquisitionSpec) DeepCopyInto(out *AcquisitionSpec) {
	*out = *in
	if in.DHCPv6PD != nil {
		in, out := &in.DHCPv6PD, &out.DHCPv6PD
		*out = new(DHCPv6PDSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RouterAdvertisement != nil {
		in, out := &in.RouterAdvertisement, &out.RouterAdvertisement
		*out = new(RouterAdvertisementSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquisitionSpec.
func (in *AcquisitionSpec) DeepCopy() *AcquisitionSpec {
	if in == nil {
		return nil
	}
	out := new(AcquisitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressRangeSpec) DeepCopyInto(out *AddressRangeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressRangeSpec.
func (in *AddressRangeSpec) DeepCopy() *AddressRangeSpec {
	if in == nil {
		return nil
	}
	out := new(AddressRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressRangeStatus) DeepCopyInto(out *AddressRangeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressRangeStatus.
func (in *AddressRangeStatus) DeepCopy() *AddressRangeStatus {
	if in == nil {
		return nil
	}
	out := new(AddressRangeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPv6PDSpec) DeepCopyInto(out *DHCPv6PDSpec) {
	*out = *in
	if in.RequestedPrefixLength != nil {
		in, out := &in.RequestedPrefixLength, &out.RequestedPrefixLength
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPv6PDSpec.
func (in *DHCPv6PDSpec) DeepCopy() *DHCPv6PDSpec {
	if in == nil {
		return nil
	}
	out := new(DHCPv6PDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicPrefix) DeepCopyInto(out *DynamicPrefix) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicPrefix.
func (in *DynamicPrefix) DeepCopy() *DynamicPrefix {
	if in == nil {
		return nil
	}
	out := new(DynamicPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicPrefix) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicPrefixList) DeepCopyInto(out *DynamicPrefixList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamicPrefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicPrefixList.
func (in *DynamicPrefixList) DeepCopy() *DynamicPrefixList {
	if in == nil {
		return nil
	}
	out := new(DynamicPrefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicPrefixList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicPrefixSpec) DeepCopyInto(out *DynamicPrefixSpec) {
	*out = *in
	in.Acquisition.DeepCopyInto(&out.Acquisition)
	if in.AddressRanges != nil {
		in, out := &in.AddressRanges, &out.AddressRanges
		*out = make([]AddressRangeSpec, len(*in))
		copy(*out, *in)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]SubnetSpec, len(*in))
		copy(*out, *in)
	}
	if in.Transition != nil {
		in, out := &in.Transition, &out.Transition
		*out = new(TransitionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicPrefixSpec.
func (in *DynamicPrefixSpec) DeepCopy() *DynamicPrefixSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicPrefixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicPrefixStatus) DeepCopyInto(out *DynamicPrefixStatus) {
	*out = *in
	if in.LeaseExpiresAt != nil {
		in, out := &in.LeaseExpiresAt, &out.LeaseExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.AddressRanges != nil {
		in, out := &in.AddressRanges, &out.AddressRanges
		*out = make([]AddressRangeStatus, len(*in))
		copy(*out, *in)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]SubnetStatus, len(*in))
		copy(*out, *in)
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]PrefixHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicPrefixStatus.
func (in *DynamicPrefixStatus) DeepCopy() *DynamicPrefixStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicPrefixStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixHistoryEntry) DeepCopyInto(out *PrefixHistoryEntry) {
	*out = *in
	in.AcquiredAt.DeepCopyInto(&out.AcquiredAt)
	if in.DeprecatedAt != nil {
		in, out := &in.DeprecatedAt, &out.DeprecatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixHistoryEntry.
func (in *PrefixHistoryEntry) DeepCopy() *PrefixHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(PrefixHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterAdvertisementSpec) DeepCopyInto(out *RouterAdvertisementSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterAdvertisementSpec.
func (in *RouterAdvertisementSpec) DeepCopy() *RouterAdvertisementSpec {
	if in == nil {
		return nil
	}
	out := new(RouterAdvertisementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSpec) DeepCopyInto(out *SubnetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSpec.
func (in *SubnetSpec) DeepCopy() *SubnetSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetStatus) DeepCopyInto(out *SubnetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetStatus.
func (in *SubnetStatus) DeepCopy() *SubnetStatus {
	if in == nil {
		return nil
	}
	out := new(SubnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionSpec) DeepCopyInto(out *TransitionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionSpec.
func (in *TransitionSpec) DeepCopy() *TransitionSpec {
	if in == nil {
		return nil
	}
	out := new(TransitionSpec)
	in.DeepCopyInto(out)
	return out
}
